name = "LAPM"
uuid = "900d2f21-6802-4fdd-aec4-3593e8a631ba"
version = "1.0.0-DEV"
authors = ["lmiq <lmartine@unicamp.br> and contributors"]

[deps]
MolSimToolkit = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"

[compat]
MolSimToolkit = "1.31.1"
PDBTools = "3.11.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
